### ISSUE TITLE
X-Ray traces don't show related CloudWatch Logs

### ISSUE THREAD

**Issue by NickDarvey** [aws-observability/aws-otel-dotnet#27]
I'm using ADOT .NET SDK and the ADOT Collector.

I can view traces in X-Ray, however related logs aren't shown.

```
Logs
All logs for this trace

No data found.
Try adjusting the dashboard time range or log query.
```

<details>
<img src="https://user-images.githubusercontent.com/6076697/154216287-2f644ab8-bb71-4025-95f5-dfa7dd71a34f.png"/>
</details>

If I tap 'View in CloudWatch Insights' it'll materialize a query which returns no logs:
```
fields @log, @timestamp, @message
| filter @message like "1-620ca1d6-07f7494e51e410242c9d67f3"
| sort @timestamp, @message desc
```

however the correct query, fixing the trace ID to remove the leading digit and hyphens, returns related logs:
```
fields @log, @timestamp, @message
| filter @message like "620ca1d607f7494e51e410242c9d67f3"
| sort @timestamp, @message desc
```

Is this expected behaviour?

#### System info

<details>

```
    <PackageVersion Include="OpenTelemetry.Contrib.Extensions.AWSXRay" Version="1.1.0" />
    <PackageVersion Include="OpenTelemetry.Contrib.Instrumentation.AWS" Version="1.0.1" />
    <PackageVersion Include="OpenTelemetry.Exporter.Console" Version="1.1.0" />
    <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.1.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.0.0-rc9" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Http" Version="1.0.0-rc9" />
```

```
amazon/aws-otel-collector:latest
```

</details>

**Comment by willarmiros** [comment]
Hi @NickDarvey,

Unfortunately, the trace <-> Log correlation feature in serviceLens is not yet officially supported. It's great to hear you have a workaround to get to view them. Can you share how you inject the trace ID into each of your log statements to possibly help other users achieve this same workaround? Could you also share the (redacted as necessary) raw trace JSON of an example trace you're viewing?

As a long-term fix, ServiceLens should try to query for trace IDs using both the X-Ray format (with the `1` and hyphens) AND the OTel format, which was the format that worked for you.

**Comment by NickDarvey** [comment]
Ahh, I just used `OpenTelemetry.Contrib.Extensions.AWSXRay` and followed the sample application to add:
https://github.com/aws-observability/aws-otel-dotnet/blob/a6c4dcabf67656d852bf258c603415265c432bba/integration-test-app/integration-test-app/Startup.cs#L32

It looks like @lupengamzn did the magic:
[open-telemetry/opentelemetry-dotnet-contrib/src/OpenTelemetry.Contrib.Extensions.AWSXRay/AWSXRayIdGenerator.cs](
https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/5f4fce1e8826cb82e40f5300bee6e5b16f862b2e/src/OpenTelemetry.Contrib.Extensions.AWSXRay/AWSXRayIdGenerator.cs#L26-L30)

**Comment by willarmiros** [comment]
Got it, thanks for the context! I've opened this feature request to search for both formats with the ServiceLens team, and will update this issue if anything comes from it. I think many customers could benefit from both formats being searched by default.

**Comment by KieranFleckney** [comment]
Thank you @NickDarvey for providing a solution, really helped me out.

@willarmiros Is there any update on ServiceLens team?

I just wanted to add a solution to help get the logs to show in service lens without having to do what @NickDarvey suggested.


Requirements: 
- follow @NickDarvey instruction to setup x-ray open telemetry compatible Id's
- Using console logger or any logger that supports `Log scopes`


First you will need to add a middleware to your application like this
```
public class XrayScopedLoggingMiddleware
{
    private readonly RequestDelegate next;
    private readonly ILogger<XrayScopedLoggingMiddleware> logger;

    public XrayScopedLoggingMiddleware(RequestDelegate next, ILogger<XrayScopedLoggingMiddleware> logger)
    {
        this.next = next ?? throw new System.ArgumentNullException(nameof(next));
        this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    public async Task Invoke(HttpContext context)
    {

        var xrayId = ConvertIdToXrayId(Activity.Current?.RootId ?? "");
        
        var loggerState = new XrayLogScope(new List<KeyValuePair<string, object?>>()
        {
            new("XrayTraceId",xrayId)
        });

        using (logger.BeginScope(loggerState))
        {
            await next(context);
        }
    }

    internal static string ConvertIdToXrayId(string id)
    {
        if (string.IsNullOrWhiteSpace(id)) return id;
        return $"1-{id[..8]}-{id[8..]}";
    }
}

internal class XrayLogScope : ReadOnlyCollection<KeyValuePair<string, object?>>
{
    public override string ToString()
    {
            StringBuilder sb = new StringBuilder();

            sb.Append(this[0].Key);
            sb.Append(':');
            sb.Append(this[0].Value);

            for (int i = 1; i < Count; i++)
            {
                sb.Append(", ");
                sb.Append(this[i].Key);
                sb.Append(':');
                sb.Append(this[i].Value);
            }

            return sb.ToString();
    }

    public XrayLogScope(IList<KeyValuePair<string, object?>> list) : base(list)
    {
    }
}

```

Then you need to register the middleware before any other.
Program.cs
```
... 
var app = builder.Build();
app.UseMiddleware<XrayScopedLoggingMiddleware>();
// ... other middleware
```

This will now include the trace id in x-ray format to all logs. Hopefully this is only a short term fix.
Example
```
info: TestProject.WeatherController
      => SpanId:f6538c55103be793, TraceId:63035fd77b3d83ea68fbcf1e6c59b71c, ParentId:0000000000000000 => ConnectionId:0HMK45HBUND3D => RequestPath:/weather RequestId:0HMK45HBUND3D:00000004 => XrayTraceId:1-63
035fd7-7b3d83ea68fbcf1e6c59b71c => TestProject.WeatherController.Post (TestProject)
      "hello world"
```

Hope this can help someone else too
