### ISSUE TITLE
.NET sample app and documentation updated for metrics GA

### ISSUE THREAD

**Issue by mhausenblas** [aws-observability/aws-otel-dotnet#32]
When [.NET SDK](https://github.com/open-telemetry/opentelemetry-dotnet) goes GA for metrics make sure that:

1. The sample and tests are up to date.
2. The relevant parts of the ADOT docs are updated.

Note: this SDK is a dependency of our ADOT [Lambda](https://aws-otel.github.io/docs/getting-started/lambda) offering.

**Comment by jeastham1993** [comment]
Just a note on the documentation, the Lamda layer works with .NET 6. The link below just needs updating, and we should probably remove .NET Core 2.1 as it's no longer supported.

https://aws-otel.github.io/docs/getting-started/lambda/lambda-dotnet#requirements

**Comment by Kausik-A** [comment]
https://github.com/aws-observability/aws-otel-community/pull/240 - Up for review

**Comment by humivo** [comment]
The .NET sample app is updated to match the standardized specification and integrations tests pass.  The ADOT documentation has also been updated to include the new sample app as well as support metrics as seen [here](https://aws-otel.github.io/docs/getting-started/dotnet-sdk/manual-instr).
