### ISSUE TITLE
AWS OTEL Breaks AmazonAutoScalingClient

### ISSUE THREAD

**Issue by Bob343** [aws-observability/aws-otel-dotnet#38]
I've created an AWS support ticket under enterprise support as well, but that's having troubles so figured I'd also open an issue here since it more directly relates to this OTEL library.

We have a .NET application using OTEL, including this package. We originally just had SSM plugged in and that was working fine - we recently added ASG calls to the application and immediately ran into issues. With the AWS instrumentation enabled, the constructor for the ASG client immediately throws an exception. 

Exception message:
"Cannot find a handler of type EndpointResolver"

Stack Trace:
   at Amazon.Runtime.Internal.RuntimePipeline.AddHandlerAfter[T](IPipelineHandler handler)
   at Amazon.Runtime.Internal.RuntimePipelineCustomizerRegistry.ApplyCustomizations(Type type, RuntimePipeline pipeline)
----Removed line referencing the method call in Program.cs since this has personal information in it----

Steps to Reproduce:
It's extremely simple to reproduce and doesn't require any credentials/IAM role/etc:

1. Create a blank console .NET app, I did .NET 6.
2. Add AWSSDK, AWSSDK.AutoScaling, core OTEL packages, and the AWS OTEL package:
![image](https://user-images.githubusercontent.com/15220647/201110666-0689f031-05b0-43dd-83f7-a2d952aa5cdc.png)
3. Add initialization code for OTEL, include the AWS instrumentation.
4. Attempt to create an AmazonAutoScalingClient
5. Exception is thrown
6. Comment out line for AWS instrumentation
7. Rerun 
8. Exception is no longer thrown (need credentials at this point).

This is what an entire test app looks like:
![image](https://user-images.githubusercontent.com/15220647/201110951-b7b0ca89-e154-4f63-9634-3749f121085d.png)

I've attached a ZIP here containing an extremely simple console app that has all of the above - I understand the security around arbitrarily running code uploaded by someone random, but it can be used as a reference for creating your own console app. Commenting out line 15 (.AddAWSInstrumentation()) makes the ASG client work fine.

[AWSSDKTest - minimal repo.zip](https://github.com/aws-observability/aws-otel-dotnet/files/9981343/AWSSDKTest.-.minimal.repo.zip)

Let me know if I can provide any other information!

**Comment by Aneurysm9** [comment]
Thank you for the report.  Could I trouble you to recreate this issue upstream in the https://github.com/open-telemetry/opentelemetry-dotnet-contrib repository?  That is where the code in question lives and having the issue there may also obtain visibility from the OTel .NET community.

**Comment by Bob343** [comment]
Hi - I opened issue [#799](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/799) on that repository. Let me know if this issue should be closed here, thanks!

**Comment by vsakaram** [comment]
Thanks for checking and closing this issue here since [#799](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/799) seems to have been closed already as it is addressed as part of [#726](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/726)
